### PR TITLE
Feature/142 time series controls

### PR DESCRIPTION
**Pull request by mohitb3**
Added the time controls to the plots https://github.com/USACE/water-ui/issues/142. I originally used radio buttons for selecting the different date ranges like in the mockup, but it didn't look very clean imo so I changed it to a dropdown.

I also reorganized a lot of the files. I moved the Autocomplete, Dropdown, and Searchbox components into a new directory `/src/app-common/inputs`, in the future if we create any new input components we can put it here. I also moved all of the location detail components to `/src/app-pages/map/location-details` (these are components like the LocationStreamControls, DamProfile, TimeSeries, etc.). 

While I was working on this, I realized we don't really need the Location page. Last week Brett said to store the map location in  the url so that people can bookmark it. We can do something like `/water/map?locationCode=:locationCode`. If we do that, then we don't need the Location page since both pages will show the same data. This would also get rid of that when transitioning from the /map route to the /location route because we won't have to switch routes when making the location detail full screen.

### CODE REVIEW

**Comment by mohitb3** [comment]
The time series endpoint doesn't seem to work if you try to get data from a previous year. For example https://cwms-data.usace.army.mil/cwms-data/timeseries?office=NWDM&name=OAHE.*&begin=2020-01-01&end=2020-01-31&format=json works, but if I change begin to `begin=2019-12-31` it gets stuck on loading.

**Comment by brian428** [comment]
hmm yeah I'm not sure, seems like a RADAR bug. I tried a few other variations like specifying the time zone and swapping the start/end to see if that mattered, but these don't seem to work either:


https://cwms-data.usace.army.mil/cwms-data/timeseries?office=NWDM&name=OAHE.*&begin=2019-11-19&end=2020-11-18&format=json&timezone=US/Central

https://cwms-data.usace.army.mil/cwms-data/timeseries?office=NWDM&name=OAHE.*&begin=2020-11-18&end=2019-11-18&format=json&timezone=US/Central

So I guess just leave it for now, and I'll see if I can find out what the RADAR issue is or if someone over there can fix it.

**Comment by brian428** [comment]
And if we just ignore this for now, is this PR still OK to merge? Or did you have anything else to push first?

**Comment by mohitb3** [comment]
> And if we just ignore this for now, is this PR still OK to merge? Or did you have anything else to push first?

Nope I don't have anything else to push, we can merge it

**Pull request merged**
