### PR TITLE
Feature/134 parse time series names

### PR DESCRIPTION
**Pull request by dlin2102**

### CODE REVIEW

**Comment by brian428** [comment]
Dan can you add a unit test that exercises some of the translation logic? That we we can add onto the test if needed to make sure the parsing is working as expected, given a variety of input strings.

**Comment by brian428** [comment]
Also just to add, this might be a good chance to figure out how to write a test that actually creates/uses a bundle, since I don't think we've done that yet and I'm not sure how easy or hard it is to test bundle logic. But since the bundles have a good amount of logic, it probably makes sense for us to know how to test it. See what you can figure out.

**Comment by brian428** [comment]
Just thinking about it, it may involve either having the test call the `composeBundles()` function in `bundles/index.js`, or have the test do it's own `composeBundles()`, and then manually dispatching actions to trigger things in the bundles?

This test from the redux-bundler repo itself may help as a reference: https://github.com/HenrikJoreteg/redux-bundler/blob/master/test/create-reactor-bundle.js

**Review by mohitb3 — APPROVED** [review]

**Comment by brian428** [comment]
Dan, I'll merge this in but I won't delete the branch. You can open another PR for the test on the same branch. Sound good?

**Pull request merged**
