### PR TITLE
Add source param to the map url

### PR DESCRIPTION
**Pull request by mohitb3**
https://github.com/USACE/water-ui/issues/194

I put all of the bundles dealing with location data in `/app-bundles/location-bundles/` and put all of the report bundles in `/app-bundles/report-bundles/`. I also renamed the location bundles which only deal with cwms data to cwms, so:
`locationDetail` -> `cwmsDetail`
`locationLevel` -> `cwmsLevel`
`locationChildren` -> `cwmsChildren`
`streamLocations` -> `cwmsStreams`

Also on a side note, I updated the DamProfile component so that it doesn't need to rely on the useMemo and got rid of the Dam Profile Table since we have the actual svg working now.

### CODE REVIEW

**Review by dlin2102 — APPROVED** [review]
Everything makes sense to me. I'm getting 404s locally but I assume that's bc the backend isn't updated yet? Also, I pushed up a small adjustment to dam profile, to reorder the gradient labels.

**Comment by mohitb3** [comment]
Yea backend isn't updated yet with the new routes. I think @brian428 has the backend changes ready to push but was waiting for the frontend to finish updating. If you go back two commits to e501279656062248fe933a7c53317376a87cfa32 you can test the frontend against the current endpoints in dev.

**Comment by brian428** [comment]
Sounds good! I will merge the API PR and then merge this one and we can check for any problems.

**Comment by brian428** [comment]
FYI something broke so I'll take a look. I think it's on the server side somewhere but I'll try to make sure and fix it if I can.

**Comment by brian428** [comment]
I think I fixed it. Everything seems to work on the A2W AWS site!

**Pull request merged**
