### PR TITLE
Feature/43 location info tab

### PR DESCRIPTION
**Pull request by dlin2102**

### CODE REVIEW

**Comment by brian428** [comment]
Dan, take a look at [the other updated test classes](https://github.com/USACE/water-ui/blob/develop/src/app-common/tests/SearchBox.test.js) and try to refactor your test to use the Jest `beforeEach()`, `it()`, `describe()`, etc. Talk to Mohit if necessary since he's the one who suggested the changes in the other tests.

**Comment by dlin2102** [comment]
I altered the scroll a little using my virtualbox. But my virtualbox isn't reliable so I wanted to confirm that it looks okay. Also, just fyi, I fixed the bits of the accordion showing in my other pull request.

**Comment by brian428** [comment]
I was still seeing the scrollbar when collapsed, so I tweaked the CSS to only turn on the overflow-y if the panel is expanded. That seemed to do the trick, if you want to double check it on your end.

**Comment by dlin2102** [comment]
yep, works for me.

**Pull request merged**
