### PR TITLE
#170 time series plot sizing

### PR DESCRIPTION
**Pull request by brian428**
Using `cloneElement()` in the Accordion seems to allow passing in an additional `visible` prop, but also seems to make the chart's initial width get calculated correctly. Meaning the initial size is calculated correctly *without* me having to do anything with the `visible` prop. Does anyone see an issue with using `cloneElement()`? I'm not sure what the pros and cons of this are. 

From what I read, the other option to let a component append additional props to a "pass through" component is to pass in the constructor instead of an instance. e.g. pass in `TimeSeriesSection` instead of `<TimeSeriesSection/>, and then the accordion would create the instance and append the visible prop. So instead of the accordion just outputting `{content}`, it would do `<content visible={flag}/>`. 

But if either of you know of other ways to do this, just let me know.

### CODE REVIEW

**Comment by brian428** [comment]
To be clear, even though this seems to fix the plot sizing without having to actually use the visible prop, I still think it's a good idea to pass visible into the accordion children, since I can imagine we'll likely have cases where we DO want to defer rendering of things in the children until they are expanded. "Expensive things" like plots, big tables, etc.

**Comment by mohitb3** [comment]
I pushed up a simpler fix where the accordion content is only rendered when that accordion section is open

**Comment by dlin2102** [comment]
Hmm I like the simpler approach but with that, it seems like when I open the accordion in not full mode and then go to full mode, it takes a second to adjust the width of the plot. But with cloneElement, it doesn't take the second bc it switches visible back to false when you do the page change.

Actually, is that happening for anyone else? I try debugging why it wasn't working with the simpler approach bc the page was unmounting so it should work but now it works for me.

**Comment by brian428** [comment]
Right, one other concern is that once the content is rendered, if they close it again, the state of that child is lost. So I assume if you open the time series, change the selected chart, close it, then open it again, it'll default back to chart 0. 

What do you guys think? Is it better to do what Mohit has (conditional render for the whole component), or always render the component, but pass a visible prop in so the component state is maintained and the component decides what (if anything) to conditionally render within itself (based on visible being true or false)?

**Comment by brian428** [comment]
We could even get fancier and add a `lazy` flag to the accordion config. If true, it does what Mohit has (only render it if it is active), if false, it always renders it. Either way, I still think passing visible into the children could be useful, so the component can also be aware of whether it is visible or not. Thoughts?

**Comment by mohitb3** [comment]
Oh right I forgot the component state would be erased if we did it my way. But I don't think passing visible does anything, if you just do `{ cloneElement( content ) }` it still works. We can go back to using cloneElement, though I'm not sure what it's doing behind the scenes

**Comment by brian428** [comment]
Well the point of passing visible in would mean within each child component, the component could conditionally render things within itself if it needs to. Like, for example, I thought we would need to do conditional rendering to get the plot to size itself correctly once the component was visible. For some reason, just using cloneElement() seems to have fixed that problem but I really have no idea why! But I don't think there's any issue passing in visible as an extra prop. If the component doesn't use it then it's basically just ignored, right?

**Comment by mohitb3** [comment]
yea we can go back to doing it your original way

**Comment by brian428** [comment]
OK, will do. Out of curiosity do you have any idea why using cloneElement() fixes the initial chart width problem?

**Comment by mohitb3** [comment]
Haha I don't know, I've never used cloneElement before.

**Pull request merged**
