### PR TITLE
refactor to only fetch the locationParams when the maps page loads, instead of after every time the location detail is updated

### PR DESCRIPTION
**Pull request by mohitb3**
This is what I meant during scrum, right now the locationParams are fetched after every `LOCATIONDETAIL_FETCH_FINISHED`, but it seems like the response will always be the same since we're not changing the url params. If that is the case, then it'd be more efficient to call doLocationParamsFetch only once when the map page is initially rendered, similar to the way we call doLocationSummariesFetch. I didn't change the persist to true so the call will still happen every time you go to the map page. What do you guys think?

### CODE REVIEW

**Review by dlin2102 — COMMENTED** [review]
Hmm, that makes sense for the most part. The only thing is that if a user selects an item from the autocomplete on homepage, the fetch wouldn't happen. Maybe we could do the fetch on the home page.

**Comment by mohitb3** [comment]
Oh true I didn't think about the locations page. We can call it in the locations page directly the same way as doLocationDetailSetCode

**Comment by dlin2102** [comment]
Actually, I think we may want to put it in MapDetails Component instead. So both map and locations would have it.

**Comment by mohitb3** [comment]
Oh yea that makes more sense

**Comment by mohitb3** [comment]
I'm closing this pr since after playing around a bit I realized it introduces a couple of unnecessary edge case scenarios which make the code more complicated. Since Dan's code already works we should just use that

**Pull request closed without merging**
