### PR TITLE
Feature/remove home page map

### PR DESCRIPTION
**Pull request by dlin2102**
Got the image from pixabay.com.

### CODE REVIEW

**Comment by brian428** [comment]
Dan did you mean to close this PR? Was something wrong with it?

**Comment by dlin2102** [comment]
oops I did not. Not sure how that happened.

**Comment by brian428** [comment]
Actually, this is for @mohitb3 as well: looking at this, what would you two think about either just taking out the image altogether for now, or doing something to make the image more of a "background", behind the search area (rather than below it)? I'm just wondering if the image takes up too much space, and pushes the cards further down the page?

**Comment by brian428** [comment]
So like this screenshot from the mockups, something like this maybe?
a2w image background

**Comment by mohitb3** [comment]
Yea I like that, it makes more sense to make the image a background.

**Comment by brian428** [comment]
OK do you think you can make that change? Thanks.

**Pull request merged**
