### PR TITLE
Adding map icons

### PR DESCRIPTION
**Pull request by dlin2102**
Added temp icons from https://uxwing.com/

### CODE REVIEW

**Comment by brian428** [comment]
Dan the logic here looks good to me, but I'm not sure about the icons themselves. We found out last week that some folks from USACE are actually looking at the app now. Can you dig around online a bit more to see what the options are for icons? The issue with the ones you added is that they are transparent, so when you zoom into the map, any "stacked" icons kind of jumble up on top of each other and are hard to decipher. 

I'm not sure what the best option is so we may just have to try a few to see how they look. Maybe see if you can find any that have a white background (then I think we can alter the color by setting the color property on the OL Icon object), or maybe some that have a set background color, and last maybe some that look more like map pins (the "upside-down tear drop" shape, if you know what I mean. Sort of like these https://www.google.com/search?q=map+marker+icon). 

We may even just have to go with basic marker icons that are just different colors for now, and worry about trying to make them more specific to the location type (dam, lake, etc.) later on. We can talk about this at our scrum call.

**Comment by brian428** [comment]
Actually looking at the current site (http://water.usace.army.mil/a2w/f?p=100:1:1), looks like they really only have 2 icons, one for WQ and one for others. And they have some different colors that I think denote flood storage level. So maybe for now we just go with 2 icons, one for WQ and one for everything else....

**Comment by brian428** [comment]
Oops I forgot, you're on PTO! Don't worry about this for now we'll look into it.

**Comment by brian428** [comment]
Dan just make a note here when you have an update to this that we can take a look at. Thanks.

**Comment by dlin2102** [comment]
Sounds good. I ended up just making svgs as markers with the icons inside and in different colors. I'll let you guys know when everything is pushed up.

**Comment by brian428** [comment]
Cool, is that visible in the branch? I pulled but it looks like it's still using the older green icon for all the points. But maybe you just haven't pushed your most recent changes yet? Either that or maybe something got overwritten when you did the dev merge?

**Comment by dlin2102** [comment]
I think the pull override it. It's on my local. I'm manually making a new pin icons with the old icon inside the marker. Its taking a little longer bc I'm using a glitchy online site to edit the svg.

**Comment by brian428** [comment]
Ah makes sense. I use Inkscape locally. It's a bit confusing but it's free, if you want to give that a try.

**Comment by dlin2102** [comment]
Just pushed up the new icons. Let me know what you think.

**Comment by brian428** [comment]
Looks good but for two things: 

First: the popover box seems misaligned with the map icon (popover seems to appear a bit below the icon). Not sure if the popover is being placed with the TOP of it at the location lat/lon (so the rest of it looks like it's below it), or if the icon is actually being placed higher than the lat/lon? Or maybe even the icon has some padding in it that is making it appear higher? Take a look and let me know if you see the same thing. My first guess is the icon has some padding or something at the bottom of it.

And second: I noticed a few odd locations that still use the old green icon. Maybe we need to set a default so that even if the location type doesn't match one of the icons, it defaults to some basic pin icon?

**Comment by dlin2102** [comment]
Ok, pushed up fixes. There was an anchor attribute that I adjusted. Also added another svg for location/default.

**Pull request merged**
